name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      env:
        REALTA_USERNAME: ${{ secrets.REALTA_USERNAME }}
        REALTA_PASSWORD: ${{ secrets.REALTA_PASSWORD }}
      run: |
        mkdir target
        timestamp=$(date -u +%Y%m%d-%H%M)
        echo "TIMESTAMP=${timestamp}" >>$GITHUB_ENV
        bash produceGenericode.sh target github ${timestamp}z "${REALTA_USERNAME:-}" "${REALTA_PASSWORD:-}" DELETE-REPOSITORY-FILES-AS-WELL

    - uses: actions/upload-artifact@v2
      with:
        name: genericode-github-${{ env.TIMESTAMP }}z
        path: ./*
        #path: target/genericode-1.0-github-${{ env.TIMESTAMP }}z/*
